export const Theme = [
  "Yellow Land",
  "Blue Pottery",
  "Mandala Theme",
  "Tropical Dry",
  "Pastel Love",
  "Indian Traditional",
  "Black & Gold",
  "Teal & White",
  "Black & White",
  "Blue & White",
  "Masquerade Theme",
  "Razzle Dazzle Theme",
  "Cocktail Theme",
  "Ivory & Gold",
  "Carnival Theme",
  "Winter Wonderland",
  "Frozen Theme",
  "Princesses Theme",
  "Hello Kitty Theme",
  "Mermaid Theme",
];
